### libros all
GET http://localhost:3000/libros
Accept: application/json

### libro by id
GET http://localhost:3000/libros/5
Accept: application/json

### create libro
POST http://localhost:3000/libros
Content-Type: application/json

{
  "titulo": "TEST",
  "id_autor": 2,
  "id_genero": 1,
  "id_editorial": 3
}   

### delete libro by id
DELETE http://localhost:3000/libro/5
Accept: application/json

### update libro by id
PATCH http://localhost:3000/libros/5
Content-Type: application/json

{
  "titulo": "TEST UPDATE"
}