@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZ29uemFsb2JhcmFob25hakBnbWFpbC5jb20iLCJpYXQiOjE3Njg3ODAwMjksImV4cCI6MTc2ODc4MzYyOX0.nlDbUOEc_lKInoWSist0XrV2ecIiDdR-dzl6vfmOJsw

### libros all
GET http://localhost:3000/libros
Accept: application/json
Authorization: Bearer {{token}}

### libro by id
GET http://localhost:3000/libros/32
Accept: application/json
Authorization: Bearer {{token}}

### create libro
POST http://localhost:3000/libros
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "TEST",
  "id_autor": 2,
  "id_genero_literario": 1,
  "id_editorial": 3
}   

### delete libro by id
DELETE http://localhost:3000/libros/32
Accept: application/json
Authorization: Bearer {{token}}

### update libro by id
PATCH http://localhost:3000/libros/32
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "TEST UPDATE final"
}


### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "gonzalobarahonaj@gmail.com",
  "password": "1234"
}

### create user
POST http://localhost:3000/auth/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "gonzalobarahonaj@gmail.com",
  "password": "1234"
}